# Driver DB
spring.datasource.url=jdbc:postgresql://localhost:5432/crm
spring.datasource.jdbcUrl=${spring.datasource.url}
spring.datasource.username=crm
spring.datasource.password=crm
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.dataTable=none

# Connection pool settings
spring.datasource.hikari.maximumPoolSize=5
spring.datasource.hikari.minimumIdle=2

# Common JPA configurations
spring.jpa.show-sql=true
spring.jpa.open-in-view=false