export enum RoleTypes {
	ADMIN = 'ADMIN',
	MODERATORE = 'MODERATORE',
	REFERENTEAZIENDA = 'REFERENTEAZIENDA',
	REFERENTECLIENTE = 'REFERENTECLIENTE',
	READERAZIENDA = 'READERAZIENDA',
	READERCLIENTE = 'READERCLIENTE',
	USER = 'USER',
	READER = 'READER'
}

export enum StatusTypes {
	ACTIVE = 'ACTIVE',
	SUSPENDED = 'SUSPENDED'
}

export enum CompanyTypes {
	REFERENTE = 'REFERENTE',
	CLIENTE = 'CLIENTE'
}